### ISSUE TITLE
Error in installing scDblFinder: object ‘colBlockApply’ is not exported by 'namespace:beachmat'

### ISSUE THREAD

**Issue by amber4mint** [plger/scDblFinder#60] opened 2022-08-05 07:02 UTC
Hi,

I installed scDblFinder by `BiocManager::install("scDblFinder")`. When I ran `library(scDblFinder)`, I got this error message:
```
Error: package or namespace load failed for ‘scDblFinder’:
 object ‘colBlockApply’ is not exported by 'namespace:beachmat'
```
I tried to updated the package _beachmat_, but this error still remain unsolved.

Could you provide any suggestion for this? 
Thank you for your helping!

**Comment by plger** [comment] 2022-08-06 07:19
Please provide a session info

**Comment by amber4mint** [comment] 2022-08-07 06:22
Hi,

Thanks for the quick response!

The session info was showed below:


```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950  LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950 LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
 [1] splines   parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[10] base     

other attached packages:
 [1] sceasy_0.0.5                reticulate_1.20             gprofiler2_0.2.1           
 [4] readr_2.1.2                 circlize_0.4.15             monocle_2.16.0             
 [7] DDRTree_0.1.5               irlba_2.3.3                 VGAM_1.1-7                 
[10] Matrix_1.3-4                usethis_2.1.6               RColorBrewer_1.1-3         
[13] openair_2.8-3               stringr_1.4.0               SingleCellExperiment_1.10.1
[16] SingleR_1.2.4               SummarizedExperiment_1.18.2 DelayedArray_0.14.1        
[19] matrixStats_0.60.0          Biobase_2.50.0              GenomicRanges_1.40.0       
[22] GenomeInfoDb_1.24.2         IRanges_2.22.2              S4Vectors_0.26.1           
[25] BiocGenerics_0.36.1         ggplot2_3.3.5               cowplot_1.1.1              
[28] patchwork_1.1.1             dplyr_1.0.7                 Seurat_3.1.4               

loaded via a namespace (and not attached):
  [1] utf8_1.2.1                    tidyselect_1.1.2              RSQLite_2.2.15               
  [4] AnnotationDbi_1.50.3          htmlwidgets_1.5.4             docopt_0.7.1                 
  [7] combinat_0.0-8                grid_4.0.2                    BiocParallel_1.22.0          
 [10] Rtsne_0.15                    munsell_0.5.0                 codetools_0.2-16             
 [13] mutoss_0.1-12                 ica_1.0-3                     interp_1.1-3                 
 [16] future_1.27.0                 withr_2.5.0                   fastICA_1.2-3                
 [19] colorspace_2.0-2              ROCR_1.0-11                   listenv_0.8.0                
 [22] Rdpack_2.4                    slam_0.1-50                   GenomeInfoDbData_1.2.3       
 [25] mnormt_2.0.2                  pheatmap_1.0.12               bit64_4.0.5                  
 [28] rprojroot_2.0.3               parallelly_1.32.1             vctrs_0.3.8                  
 [31] generics_0.1.3                TH.data_1.1-1                 BiocFileCache_1.12.1         
 [34] randomForest_4.6-10           R6_2.5.1                      rsvd_1.0.5                   
 [37] bitops_1.0-7                  cachem_1.0.6                  assertthat_0.2.1             
 [40] promises_1.2.0.1              scales_1.2.0                  multcomp_1.4-19              
 [43] gtable_0.3.0                  beachmat_2.4.0                globals_0.15.1               
 [46] processx_3.7.0                sandwich_3.0-2                rlang_1.0.2                  
 [49] GlobalOptions_0.1.2           lazyeval_0.2.2                hexbin_1.28.2                
 [52] BiocManager_1.30.18           yaml_2.3.5                    reshape2_1.4.4               
 [55] httpuv_1.6.2                  tools_4.0.2                   ellipsis_0.3.2               
 [58] ggridges_0.5.3                TFisher_0.2.0                 Rcpp_1.0.7                   
 [61] plyr_1.8.6                    zlibbioc_1.34.0               densityClust_0.3.2           
 [64] purrr_0.3.4                   RCurl_1.98-1.3                ps_1.7.1                     
 [67] prettyunits_1.1.1             deldir_1.0-6                  viridis_0.6.2                
 [70] pbapply_1.5-0                 zoo_1.8-9                     ggrepel_0.9.1                
 [73] cluster_2.1.0                 fs_1.5.2                      magrittr_2.0.1               
 [76] data.table_1.14.0             lmtest_0.9-38                 RANN_2.6.1                   
 [79] tmvnsim_1.0-2                 mvtnorm_1.1-2                 fitdistrplus_1.1-8           
 [82] pkgload_1.2.4                 hms_1.1.1                     mime_0.12                    
 [85] xtable_1.8-4                  jpeg_0.1-9                    sparsesvd_0.2                
 [88] shape_1.4.6                   gridExtra_2.3                 HSMMSingleCell_1.8.0         
 [91] testthat_3.1.4                compiler_4.0.2                tibble_3.1.2                 
 [94] maps_3.4.0                    KernSmooth_2.23-17            crayon_1.5.1                 
 [97] htmltools_0.5.1.1             mgcv_1.8-31                   later_1.3.0                  
[100] tzdb_0.3.0                    tidyr_1.1.3                   lubridate_1.8.0              
[103] DBI_1.1.3                     ExperimentHub_1.14.2          dbplyr_2.1.1                 
[106] MASS_7.3-51.6                 rappdirs_0.3.3                brio_1.1.3                   
[109] cli_3.0.1                     rbibutils_2.2.3               metap_1.8                    
[112] qqconf_1.2.3                  igraph_1.2.6                  pkgconfig_2.0.3              
[115] sn_2.0.2                      numDeriv_2016.8-1.1           plotly_4.10.0                
[118] multtest_2.46.0               XVector_0.28.0                callr_3.7.1                  
[121] digest_0.6.27                 sctransform_0.3.2             RcppAnnoy_0.0.19             
[124] tsne_0.1-3.1                  leiden_0.3.9                  uwot_0.1.10                  
[127] DelayedMatrixStats_1.10.1     curl_4.3.2                    shiny_1.6.0                  
[130] lifecycle_1.0.1               nlme_3.1-148                  jsonlite_1.7.2               
[133] BiocNeighbors_1.6.0           mapproj_1.2.8                 limma_3.44.3                 
[136] desc_1.4.1                    viridisLite_0.4.0             fansi_0.5.0                  
[139] pillar_1.8.0                  lattice_0.20-41               fastmap_1.1.0                
[142] httr_1.4.3                    plotrix_3.8-2                 pkgbuild_1.3.1               
[145] survival_3.1-12               remotes_2.4.2                 interactiveDisplayBase_1.26.3
[148] glue_1.4.2                    qlcMatrix_0.9.7               FNN_1.1.3.1                  
[151] png_0.1-7                     BiocVersion_3.11.1            bit_4.0.4                    
[154] stringi_1.7.3                 blob_1.2.3                    BiocSingular_1.4.0           
[157] AnnotationHub_2.20.2          latticeExtra_0.6-30           memoise_2.0.1                
[160] mathjaxr_1.6-0                future.apply_1.9.0            ape_5.5      
```

**Comment by plger** [comment] 2022-08-07 11:55
What is your Bioconductor version? (run `BiocManager::version()` )
It seems your `beachmat` version is from 3 years ago, which suggests an old bioconductor installation (bioconductor will always install the package version of the bioc release you have to avoid conflicts). This will be hard to debug if we can't reproduce it with recent versions. At any rate I'd strongly advise to update if it's indeed that old, as in the single-cell world 2-3y is a lot...

**Comment by plger** [comment] 2022-09-14 07:44
Will close this unless you can reproduce on newer versions.

**Comment by amber4mint** [comment] 2022-09-14 07:51
Hi,

Sorry for the late reply. I've solved this error by updating the latest version of biocondutor.
Thank you for all your helping!

**Closed** 2022-09-14 07:51 UTC
