### ISSUE TITLE
scDbliFinder.sample is different from the sample column specified in `scDblFinder` function `samples` column ?

### ISSUE THREAD

**Issue by Yunuuuu** [plger/scDblFinder#66] opened 2022-11-21 03:37 UTC
Hi, I have run scDblFinder in "split" smaple mode to detect doublets with following code (since the data is large, I only provide code):
```
set.seed(221113L)
sce_qc <- scDblFinder::scDblFinder(
    sce_raw[, !sce_raw$low_lib_size],
    clusters = TRUE, dims = 50L, 
    samples = "Sample", multiSampleMode = "split",
    returnType = "sce"
)
```

When I check the results, the `scDblFinder.sample` column seems strange:
```
data.frame(colData(sce_qc)) %>%
    dplyr::select(Sample, scDblFinder.sample) %>% 
    dplyr::filter(Sample != scDblFinder.sample)
# here is some output
                   Sample scDblFinder.sample
AAACCCAAGCCTCTCT-1    B4T              B16T2
AAACCCAAGTGTAGAT-1    B4T                B1T
AAACGCTGTGTATTGC-1    B4T              B14T2
AAAGTGAGTAGATCGG-1    B4T               B16U
AACAAAGGTGGATCGA-1    B4T                B1U
AACAAGAGTCTACATG-1    B4T              B14T1
AACCAACAGGTAAACT-1    B4T                B1T
AACGGGAGTGAGATCG-1    B4T              B14T2
AAGAACATCTCTCGCA-1    B4T               B12T
AAGATAGAGCCTCATA-1    B4T                B1U
AAGATAGAGTAAGACT-1    B4T                B1T
AAGATAGCAAATGGCG-1    B4T               B16U
AAGGAATGTTGAATCC-1    B4T               B12U
```

I don't know why they are different when I used a "split" mode? From the help page of `scDblFinder`, "split" mode runs all process separated by samples, I think they should be the same, is it right?

**Comment by plger** [comment] 2022-11-21 08:26
Thanks a lot for reporting this, yes they should be the same. Fortunately the error was only in the reporting, and shouldn't have affected the doublet scores.

It error should be fixed now on the github version (would be happy if you could confirm with your dataset), and I'll push it to Bioc devel once the checks have passed.

**Comment by plger** [comment] 2022-11-27 11:05
Hi @Yunuuuu ,
could you confirm that this solved your problem? Will close the issue if there's no answer.
Pierre-Luc

**Comment by Yunuuuu** [comment] 2022-11-28 09:58
Hi, I downloaded the latest plger/scDblFinder using pak::pkg_install and restart R, it remains here:

![image](https://user-images.githubusercontent.com/19575010/204248692-d7026889-9588-4d0d-bd89-ab1805ef21a6.png)

**Comment by Yunuuuu** [comment] 2022-11-28 10:01
I checked the source code of `scDblFindeer` function, which indicates this has been modified:

![image](https://user-images.githubusercontent.com/19575010/204249259-d3a7c41f-07cb-4ae4-8329-e1b087a8348f.png)

**Comment by Yunuuuu** [comment] 2022-11-28 10:26
I try to understand the code, but I'm not familiar with the internal function:
![image](https://user-images.githubusercontent.com/19575010/204254089-35dab3c5-83a4-4b2c-abf5-9303eafef6cd.png)

when `samples` is not NULL and `returnType` is "sce" or "full", following code won't run in `scDblFinder` funtion:
```
        if (returnType == "counts") {
            for (s in names(d)) d[[s]]$sample <- s
            return(do.call(cbind, d))
        }
```

**Comment by plger** [comment] 2022-12-04 17:23
@Yunuuuu , hopefully everything is as expected now?

**Comment by Yunuuuu** [comment] 2022-12-06 06:08
I'll try this again @plger

**Comment by Yunuuuu** [comment] 2022-12-08 04:42
It remains here:
![image](https://user-images.githubusercontent.com/19575010/206358420-2a817ce3-7137-499c-bd24-5c9e42fcd96a.png)

the package GithubSHA1 is here:
![image](https://user-images.githubusercontent.com/19575010/206358229-85ebace9-82b9-492b-b387-55bfaa8ec3da.png)

**Comment by Yunuuuu** [comment] 2022-12-08 07:44
Thanks for the development of this package @plger, I'll do more test this weekend, I cannot find what's wrong now

**Comment by plger** [comment] 2022-12-08 12:19
Hi @Yunuuuu , okay now I don't get why you're having this problem, as I can't reproduce it with my toy data. Could you share a minimal example, e.g. SCE with only count matrix and sample id, only 2-300 genes, perhaps subsampling the cells? (you can rename genes & remove other cell metadata if you're worried about the data)

**Comment by Yunuuuu** [comment] 2022-12-11 17:37
Is there any method to share rds data ?

**Comment by plger** [comment] 2022-12-11 18:27
You can email it to `pierre-luc.germain@hest.ethz.ch` if it's <20mb, otherwise if you don't have a platform for sharing of larger files you can write me an email and I'll send you some details.
Thanks!

**Comment by Yunuuuu** [comment] 2022-12-12 02:03
hi, I have uploaded it to the Google Drive，and the link has been emailed to `pierre-luc.germain@hest.ethz.ch`. I can confirm this data can induce the problem. Thanks!
```
[R]> set.seed(221113L)
[R]> sce_qc <- scDblFinder::scDblFinder(
         test_data,
         clusters = TRUE, dims = 50L,
         nfeatures = 2000L,
         samples = "Sample",
         multiSampleMode = "split",
         returnType = "sce"
     )
There were 26 warnings (use warnings() to see them)

[R]> # logNormCounts
     data.frame(colData(sce_qc)) %>%
         dplyr::select(Sample, scDblFinder.sample
     ) %>% 
         dplyr::filter(Sample != scDblFinder.samp
     le) %>% 
         head()
                      Sample scDblFinder.sample
TTTCCTCTCAACTCTT-1   sample3            sample2
GTCAAACTCCACGAAT-1   sample3            sample1
GGTTAACCAGCGCTTG-1   sample3            sample2
AGCATCATCGGCTTGG-1.1 sample3            sample1
TGGAACTGTGACAGCA-1.1 sample3            sample1
```

**Comment by Yunuuuu** [comment] 2022-12-12 02:05
It seems the column cell names matters, for I have some duplicated column names ? By changing colnames with `colnames(test_data) <- paste0("cell_", seq_len(ncol(test_data)))`, this problem can be figured out.
```

[R]> colnames(test_data) <- paste0("cell_", seq_l
     en(ncol(test_data)))

[R]> set.seed(221113L)

[R]> sce_qc <- scDblFinder::scDblFinder(
         test_data,
         clusters = TRUE, dims = 50L,
         nfeatures = 2000L,
         samples = "Sample",
         multiSampleMode = "split",
         returnType = "sce"
     )
There were 28 warnings (use warnings() to see them)

[R]> # logNormCounts
     data.frame(colData(sce_qc)) %>%
         dplyr::select(Sample, scDblFinder.sample
     ) %>% 
         dplyr::filter(Sample != scDblFinder.samp
     le) %>% 
         head()
[1] Sample             scDblFinder.sample
<0 rows> (or 0-length row.names)
```

**Comment by plger** [comment] 2022-12-13 11:50
Ok, thanks @Yunuuuu , that explains a lot.
I'm afraid I'm going to have to throw an error msg on duplicated colnames, because I need to match the cells with the original object (to provide the full original object with added slots).

**Comment by Yunuuuu** [comment] 2022-12-14 00:54
@plger Thanks a lot, enforcing unique colnames have already solved this.

**Closed** 2022-12-14 13:42 UTC
